---
- name: Download nbdkit SRPM
  command: yumdownloader --source nbdkit
  args:
    chdir: "{{ v2v_build_dir }}"
    creates: "{{ v2v_build_dir }}/nbdkit-*.src.rpm"

- name: Identify nbdkit SRPM
  find:
    paths: "{{ v2v_build_dir }}"
    patterns: "nbdkit-[0-9]*.src.rpm"
    recurse: "no"
    use_regex: "no"
  register: nbdkit_srpm

# Ignore ansible-lint rule 303 "rpm used in place of yum or rpm_key module
- name: Extract nbdkit SRPM
  command: >
    rpm --install
    --define "_topdir {{ v2v_build_dir|quote }}"
    --define "_sourcedir {{ v2v_build_dir|quote }}"
    --define "_specdir {{ v2v_build_dir|quote }}"
    "{{ nbdkit_srpm.files[0].path }}"
  args:
    chdir: "{{ v2v_build_dir }}"  # noqa 303
    creates: "{{ v2v_build_dir }}/nbdkit-plugin-vddk.spec*"
