---
- name: Prepare
  hosts: all

  tasks:

    - name: install v2v-conversion-host-wrapper
      yum:
        name: "https://github.com/oVirt/v2v-conversion-host/releases/download/v1.11.0/\
              v2v-conversion-host-wrapper-1.11.0-1.el7.noarch.rpm"
        state: present
      register: my_result
      until: my_result is succeeded

    - block:

        - name: check director /root/.ssh
          file:
            path: /root/.ssh
            state: directory

        - name: install python2-openstack repo
          yum:
            name: https://www.rdoproject.org/repos/rdo-release.rpm
            state: present
          register: my_result
          until: my_result is succeeded

        - name: install win virto repo
          yum:
            name: https://fedorapeople.org/groups/virt/virtio-win/repo/stable/virtio-win-0.1.141-1.noarch.rpm
            state: present
          register: my_result
          until: my_result is succeeded

      when: v2v_host_type == 'openstack'

    - block:

        - name: create user vdsm
          user:
            name: vdsm
            home: /var/lib/vdsm

        - name: check directory /var/lib/vdsm/.ssh
          file:
            path: /var/lib/vdsm/.ssh
            state: directory

        - name: install ovirt repo
          yum:
            name: https://resources.ovirt.org/pub/ovirt-4.2/rpm/el7/noarch/ovirt-release42-4.2.8-1.el7.noarch.rpm
            state: present
          register: my_result
          until: my_result is succeeded

      when: v2v_host_type == "rhv"
